#!/bin/sh
export EXIASAVER_HOME="$HOME/Documents/Project-C/"
export EXIASAVER1_PBM="$HOME/Documents/Project-C/Statique_PBM/"
export EXIASAVER2_PBM="$HOME/Documents/Project-C/Dynamique_PBM/"
export EXIASAVER2_TAILLE="5x3"
export EXIASAVER2_SLEEP="5"
export EXIASAVER3_PBM="$HOME/Documents/Project-C/Interactif_PBM/"
export EXIASAVER1="$HOME/Documents/Project-C/statique"
export EXIASAVER2="$HOME/Documents/Project-C/dynamique"
export EXIASAVER3="$HOME/Documents/Project-C/interactif"
export EXIASAVER_HIS="$HOME/Documents/Project-C/historique"
